#!/usr/bin/env bash
set -x

# variables
SCRIPT_PATH=$(dirname $0)
VERSION=${1:-0.0.0-1}
APP_NAME="batch-liberar-saldo"
DEB_NAME="$APP_NAME-hubfintech"
RPM_NAME="$APP_NAME-hubfintech"
TMP_DEB_DIR="/tmp/$APP_NAME-hubfintech-VERSION_ARCH.deb"
TMP_RPM_DIR="/tmp/$APP_NAME-hubfintech-VERSION_ARCH.rpm"
APP_DIR="/opt/vp/app"
INSTALLATION_DIR="$APP_DIR/$APP_NAME"
PIDS_DIR="$APP_DIR/pids/$APP_NAME"
LOGS_DIR="$APP_DIR/logs/$APP_NAME"
CURRENT_DEPLOY="$INSTALLATION_DIR/current"

# requirements
fpm -h >/dev/null 2>&1 || { echo >&2 "fpm is required!"; exit 1; }
rsync --version >/dev/null 2>&1 || { echo >&2 "rsync is required!"; exit 1; }

[[ -w $CURRENT_DEPLOY ]] || { echo >&2  "$CURRENT_DEPLOY is not writable by the user"; exit 1; }

cp ./target/$APP_NAME*.jar $CURRENT_DEPLOY/$APP_NAME.jar || exit 1

# generating .deb file
fpm -s dir \
	-t deb \
	-n $DEB_NAME \
	-v $VERSION \
	--description "$APP_NAME v$1" \
	--before-install $SCRIPT_PATH/before-install.sh \
	--package $TMP_DEB_DIR \
	-C / \
	${CURRENT_DEPLOY}

# generating .rpm file
fpm -s dir \
	-t rpm \
	-n $RPM_NAME \
	-v $VERSION \
	--description "$APP_NAME v$1" \
	--before-install $SCRIPT_PATH/before-install.sh \
	--package $TMP_RPM_DIR \
	-C / \
	${CURRENT_DEPLOY}
